const $ = id => document.getElementById(id);
const key = 'paper-calendar-v1';
const googleClientId = '477659561112-19g3hkek2d4bn408bed5feoa96nu19hq.apps.googleusercontent.com';
const state = JSON.parse(localStorage.getItem(key) || '{"events":[]}');
state.events=state.events.filter(e=>!e.googleId);
let monday = startOfWeek(new Date());
let accessToken = '';
let tokenClient;
let pending = null;
const fmt = d => [d.getFullYear(), String(d.getMonth()+1).padStart(2,'0'), String(d.getDate()).padStart(2,'0')].join('-');
const day = s => new Date(s+'T12:00:00');
function startOfWeek(d){let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-(x.getDay()+6)%7);return x}
function shiftDate(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function save(){localStorage.setItem(key,JSON.stringify({...state,events:state.events.filter(e=>!e.googleId)}))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(e){return `${e.date} ${e.start}–${e.end} · ${e.title}`}
function render(){const last=shiftDate(monday,6);$('week').textContent=`${monday.toLocaleDateString('ru',{day:'numeric',month:'long'})} — ${last.toLocaleDateString('ru',{day:'numeric',month:'long',year:'numeric'})}`;$('days').innerHTML=Array.from({length:7},(_,i)=>{const d=shiftDate(monday,i),date=fmt(d),events=state.events.filter(e=>e.date===date).sort((a,b)=>a.start.localeCompare(b.start));return `<div class="day"><div class="dayhead">${d.toLocaleDateString('ru',{weekday:'short'})}<b>${d.getDate()}</b></div>${events.map(e=>`<div class="event ${e.source==='draft'?'draft':''} ${e.cancelled?'cancelled':''}">${esc(e.start)}–${esc(e.end)}<strong>${esc(e.title)}</strong><small>${e.source==='draft'?'Черновик':'В календаре'}${e.course?' · '+esc(e.course):''}</small></div>`).join('')}</div>`}).join('');$('drafts').innerHTML=state.events.filter(e=>e.source==='draft').map(e=>`<div class="draft-card"><strong>${esc(e.title)}</strong>${esc(e.date)} · ${esc(e.start)}–${esc(e.end)}${e.course?' · '+esc(e.course):''}<div><button data-edit="${esc(e.id)}">Изменить</button><button data-publish="${esc(e.id)}">Подтвердить</button><button data-remove="${esc(e.id)}">Удалить</button></div></div>`).join('')||'<p>Черновиков пока нет.</p>';$('status').textContent=accessToken?'Google подключён':'Локальный режим'}
function ask(title,items,action){pending=action;$('confirm').querySelector('h2').textContent=title;$('details').innerHTML=items.map(s=>`<div class="detail">${esc(s)}</div>`).join('');$('confirm').showModal()}
function log(s){$('log').textContent+='\n\n'+s;$('log').scrollTop=$('log').scrollHeight}
function validate(date,start,end){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&/^\d\d:\d\d$/.test(start)&&/^\d\d:\d\d$/.test(end)&&end>start}
$('prev').onclick=()=>{monday=shiftDate(monday,-7);render();loadGoogle()};$('next').onclick=()=>{monday=shiftDate(monday,7);render();loadGoogle()};$('today').onclick=()=>{monday=startOfWeek(new Date());render();loadGoogle()};$('date').value=fmt(new Date());
let photoImage=null, selection=null, dragStart=null, recognizer=null, photoUrl=null, blocks=[];
const canvas=$('crop'),ctx=canvas.getContext('2d');
function redraw(){if(!photoImage)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(photoImage,0,0,canvas.width,canvas.height);blocks.forEach((block,i)=>{ctx.strokeStyle='#bd7137';ctx.lineWidth=3;ctx.strokeRect(...block.rect);ctx.fillStyle='#bd7137';ctx.fillRect(block.rect[0],block.rect[1],22,20);ctx.fillStyle='white';ctx.font='bold 14px sans-serif';ctx.fillText(String(i+1),block.rect[0]+6,block.rect[1]+15)});if(selection){ctx.fillStyle='#246f7040';ctx.strokeStyle='#246f70';ctx.lineWidth=3;ctx.fillRect(...selection);ctx.strokeRect(...selection)}}
function point(ev){const r=canvas.getBoundingClientRect();return {x:(ev.clientX-r.left)*canvas.width/r.width,y:(ev.clientY-r.top)*canvas.height/r.height}}
function showLoupe(ev){if(!photoImage)return;const p=point(ev),loupe=$('loupe'),l=loupe.getContext('2d');l.imageSmoothingEnabled=false;l.fillStyle='white';l.fillRect(0,0,loupe.width,loupe.height);l.drawImage(photoImage,(p.x-30)*photoImage.width/canvas.width,(p.y-20)*photoImage.height/canvas.height,60*photoImage.width/canvas.width,40*photoImage.height/canvas.height,0,0,loupe.width,loupe.height);const r=canvas.getBoundingClientRect();loupe.style.left=Math.max(0,Math.min(r.width-180,ev.clientX-r.left+12))+'px';loupe.style.top=Math.max(0,ev.clientY-r.top-140)+'px';loupe.hidden=false}
canvas.onpointerdown=ev=>{dragStart=point(ev);canvas.setPointerCapture(ev.pointerId)};
canvas.onpointermove=ev=>{showLoupe(ev);if(!dragStart)return;const p=point(ev);selection=[Math.min(p.x,dragStart.x),Math.min(p.y,dragStart.y),Math.abs(p.x-dragStart.x),Math.abs(p.y-dragStart.y)];redraw()};
canvas.onpointerleave=()=>$('loupe').hidden=true;
canvas.onpointerup=()=>{dragStart=null;const small=!selection||selection[2]<10||selection[3]<5;$('recognize').hidden=small;$('addBlock').hidden=small};
function renderBlocks(){$('blocks').hidden=!blocks.length;$('blockList').innerHTML=blocks.map((block,i)=>`<div class="block-card"><span>Фрагмент ${i+1}${block.attempted&&!block.text?' · не прочитан':''}</span><input data-block-text="${i}" aria-label="Текст фрагмента ${i+1}" value="${esc(block.text||'')}" placeholder="${block.attempted?'Введите текст вручную':'Текст после распознавания'}"><button data-use-block="${i}" aria-label="Перенести фрагмент ${i+1} в название">В название</button><button data-remove-block="${i}" aria-label="Удалить фрагмент ${i+1}">×</button></div>`).join('');redraw()}
function loadPhoto(file){if(!file)return;if(!file.type.startsWith('image/')){$('ocrStatus').textContent='Нужен файл изображения.';return}const nextUrl=URL.createObjectURL(file),img=new Image();img.onload=()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=nextUrl;photoImage=img;const scale=Math.min(1,1000/img.width);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);selection=null;blocks=[];renderBlocks();$('photoTools').hidden=false;$('photoWorkspace').hidden=false;$('photoZoom').value='100';$('zoomValue').textContent='100%';canvas.style.width='100%';$('recognize').hidden=true;$('addBlock').hidden=true;$('dropzone').classList.add('has-photo');$('dropzone').querySelector('strong').textContent='Фото загружено';$('dropzone').querySelector('span').textContent='Перетащите другое или нажмите для замены';redraw();$('ocrStatus').textContent='Выделите запись на фото. Для мелкого текста увеличьте масштаб.'};img.onerror=()=>{URL.revokeObjectURL(nextUrl);$('ocrStatus').textContent='Не удалось открыть изображение.'};img.src=nextUrl}
$('photoZoom').oninput=()=>{const zoom=+$('photoZoom').value;$('zoomValue').textContent=zoom+'%';canvas.style.width=zoom+'%';$('loupe').hidden=true};
$('addBlock').onclick=()=>{if(!selection)return;blocks.push({rect:[...selection],text:''});selection=null;$('recognize').hidden=true;$('addBlock').hidden=true;renderBlocks();$('ocrStatus').textContent=`Добавлено фрагментов: ${blocks.length}. Выделите следующий или распознайте все.`};
$('blockList').oninput=e=>{const i=e.target.dataset.blockText;if(i!==undefined&&blocks[i])blocks[i].text=e.target.value};
$('blockList').onclick=e=>{const use=e.target.dataset.useBlock,remove=e.target.dataset.removeBlock;if(use!==undefined&&blocks[use]&&blocks[use].text){$('title').value=blocks[use].text;$('title').focus()}if(remove!==undefined){blocks.splice(+remove,1);renderBlocks()}};
const dropzone=$('dropzone');
dropzone.onclick=()=>$('photo').click();
dropzone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('photo').click()}};
$('photo').onchange=()=>{loadPhoto($('photo').files[0]);$('photo').value=''};
dropzone.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';dropzone.classList.add('dragover')};
dropzone.ondragleave=e=>{if(!dropzone.contains(e.relatedTarget))dropzone.classList.remove('dragover')};
dropzone.ondrop=e=>{e.preventDefault();dropzone.classList.remove('dragover');loadPhoto([...e.dataTransfer.files].find(file=>file.type.startsWith('image/'))||e.dataTransfer.files[0])};
document.addEventListener('paste',e=>{const image=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'));if(!image)return;e.preventDefault();loadPhoto(image.getAsFile())});
async function ocrWorker(){if(recognizer)return recognizer;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';script.onload=resolve;script.onerror=()=>reject(Error('Не удалось загрузить Tesseract.js'));document.head.append(script)});recognizer=await Tesseract.createWorker('rus',1,{logger:message=>{if(message.progress!==undefined)$('ocrStatus').textContent=`Загрузка OCR: ${Math.round(message.progress*100)}%`}});await recognizer.setParameters({tessedit_pageseg_mode:Tesseract.PSM.SINGLE_LINE});return recognizer}
function selectedPhoto(rect){const [x,y,w,h]=rect,sx=photoImage.width/canvas.width,sy=photoImage.height/canvas.height,pad=Math.max(6,Math.round(h*.2));const left=Math.max(0,Math.floor((x-pad)*sx)),top=Math.max(0,Math.floor((y-pad)*sy)),right=Math.min(photoImage.width,Math.ceil((x+w+pad)*sx)),bottom=Math.min(photoImage.height,Math.ceil((y+h+pad)*sy));const piece=document.createElement('canvas');piece.width=right-left;piece.height=bottom-top;piece.getContext('2d').drawImage(photoImage,left,top,piece.width,piece.height,0,0,piece.width,piece.height);return piece}
function enhanceLine(source){const scale=Math.max(2,Math.min(4,Math.ceil(80/source.height))),piece=document.createElement('canvas');piece.width=source.width*scale+40;piece.height=source.height*scale+40;const p=piece.getContext('2d',{willReadFrequently:true});p.fillStyle='white';p.fillRect(0,0,piece.width,piece.height);p.imageSmoothingQuality='high';p.drawImage(source,20,20,source.width*scale,source.height*scale);const pixels=p.getImageData(0,0,piece.width,piece.height);for(let i=0;i<pixels.data.length;i+=4){const gray=.299*pixels.data[i]+.587*pixels.data[i+1]+.114*pixels.data[i+2];const value=Math.max(0,Math.min(255,(gray-165)*2+225));pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=value}p.putImageData(pixels,0,0);return piece}
const readable=data=>data.confidence>=45&&[...data.text.matchAll(/[А-Яа-яЁёA-Za-z]/g)].length>=3;
async function recognizeRect(rect,worker){const piece=selectedPhoto(rect);let result=await worker.recognize(enhanceLine(piece));if(!readable(result.data)){const original=await worker.recognize(piece);if(original.data.confidence>result.data.confidence)result=original}return readable(result.data)?result.data.text.trim():''}
$('recognize').onclick=async()=>{if(!selection||!photoImage)return;const rect=[...selection];$('recognize').disabled=true;$('ocrStatus').textContent='Загружаю русскую OCR-модель…';try{const worker=await ocrWorker();$('ocrStatus').textContent='Распознаю выделенный фрагмент…';const found=await recognizeRect(rect,worker);if(found)$('title').value=found;$('ocrStatus').textContent=found?'Результат помещён в название. Проверьте текст, дату и время перед добавлением.':'Не удалось уверенно прочесть фрагмент. Снимите запись крупнее или введите текст вручную.'}catch(err){$('ocrStatus').textContent='OCR не запустился: '+err.message+'. Введите текст вручную.'}finally{$('recognize').disabled=false}};
$('recognizeBlocks').onclick=async()=>{if(!blocks.length)return;$('recognizeBlocks').disabled=true;try{const worker=await ocrWorker();for(let i=0;i<blocks.length;i++){$('ocrStatus').textContent=`Распознаю фрагмент ${i+1} из ${blocks.length}…`;blocks[i].text=await recognizeRect(blocks[i].rect,worker);blocks[i].attempted=true;renderBlocks()}const count=blocks.filter(block=>block.text).length;$('ocrStatus').textContent=count?`Прочитано ${count} из ${blocks.length}. Проверьте записи и перенесите нужную в название.`:'Записи не удалось уверенно прочесть. Введите текст в полях фрагментов или снимите страницу крупнее.'}catch(err){$('ocrStatus').textContent='OCR не запустился: '+err.message}finally{$('recognizeBlocks').disabled=false}};
$('add').onsubmit=e=>{e.preventDefault();const title=$('title').value.trim(),date=$('date').value,start=$('start').value,end=$('end').value,course=$('course').value.trim();if(!validate(date,start,end))return alert('Проверьте дату и время: конец должен быть позже начала.');state.events.push({id:crypto.randomUUID(),title,date,start,end,course,source:'draft',cancelled:false});save();monday=startOfWeek(day(date));render();$('title').value='';$('course').value=''};
$('drafts').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.edit||b.dataset.publish||b.dataset.remove;const item=state.events.find(x=>x.id===id);if(!item)return;if(b.dataset.edit){const title=prompt('Название',item.title);if(title===null)return;const date=prompt('Дата ГГГГ-ММ-ДД',item.date);if(date===null)return;const start=prompt('Начало ЧЧ:ММ',item.start);if(start===null)return;const end=prompt('Конец ЧЧ:ММ',item.end);if(end===null)return;if(!title.trim()||!validate(date,start,end))return alert('Проверьте название, дату и время.');Object.assign(item,{title:title.trim(),date,start,end});save();render()}else if(b.dataset.remove){ask('Удалить черновик?',[label(item)],()=>{state.events=state.events.filter(x=>x.id!==id);save();render()})}else ask('Создать событие?',[label(item)],async()=>{if(accessToken){const result=await calendarRequest('POST','/calendars/primary/events',toGoogle(item));item.googleId=result.id}item.source='calendar';save();render()})};
$('no').onclick=()=>$('confirm').close();$('yes').onclick=async()=>{const action=pending;pending=null;$('confirm').close();if(!action)return;try{await action()}catch(err){alert('Изменение не выполнено: '+err.message)}};
function parseTime(text){const m=text.match(/(?:в|на)\s*(\d{1,2})(?::(\d{2}))?/i);if(!m)return null;const h=+m[1],min=+(m[2]||0);return h<24&&min<60?`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`:null}
function parseDate(text){const iso=text.match(/\b(\d{4}-\d{2}-\d{2})\b/);if(iso)return iso[1];if(/завтра/i.test(text))return fmt(shiftDate(new Date(),1));return fmt(new Date())}
let geminiKey='';
$('saveGemini').onclick=()=>{const value=$('geminiInput').value.trim();if(!value){$('geminiStatus').textContent='Вставьте Gemini API Key.';return}geminiKey=value;$('geminiInput').value='';$('clearGemini').hidden=false;$('geminiStatus').textContent='ИИ включён до закрытия или обновления вкладки. Отправляются команда и краткие сведения о загруженных событиях.';$('commandHelp').textContent='Пишите свободно: «что у меня завтра?», «поставь встречу в пятницу», «перенеси английский на вечер». Изменения требуют подтверждения.'};
$('clearGemini').onclick=()=>{geminiKey='';$('clearGemini').hidden=true;$('geminiStatus').textContent='ИИ отключён. Ключ удалён из памяти вкладки.';$('commandHelp').textContent='«Добавь» создаёт черновик на час. «Перенеси» меняет время, «отмени» удаляет совпадения по названию или курсу. Перед изменением покажем подтверждение.'};
const aiSchema={type:'OBJECT',properties:{action:{type:'STRING',enum:['add','move','cancel','show','unknown']},title:{type:'STRING'},date:{type:'STRING'},start:{type:'STRING'},end:{type:'STRING'},eventIds:{type:'ARRAY',items:{type:'STRING'}}},required:['action','title','date','start','end','eventIds']};
function validDate(value){return /^\d{4}-\d{2}-\d{2}$/.test(value)&&!isNaN(day(value))&&fmt(day(value))===value}
async function askGemini(text){const events=state.events.filter(e=>!e.cancelled).slice(0,80).map(e=>({id:e.id,title:e.title,date:e.date,start:e.start,end:e.end,course:e.course||''}));const prompt=`Ты разбираешь команду для календаря. Верни только JSON по схеме. Текущая дата ${fmt(new Date())}, часовой пояс ${Intl.DateTimeFormat().resolvedOptions().timeZone}. Загруженные события: ${JSON.stringify(events)}. Команда: ${JSON.stringify(text)}. Действия: add — создать черновик; move — перенести существующие события; cancel — отменить; show — показать; unknown — неясно. Для move/cancel/show выбирай eventIds только из списка. Для add укажи title, date в YYYY-MM-DD, start и end в HH:MM; если длительность не задана, один час. Для move укажи новую date и start, end оставь пустым для сохранения длительности. Если нет точного события или даты/времени, верни unknown. Ничего не придумывай.`;const response=await fetch('https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash-lite:generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':geminiKey},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseSchema:aiSchema}})});if(!response.ok)throw Error(`Gemini API ${response.status}${response.status===429?' — бесплатная квота временно исчерпана':''}`);const data=await response.json(),answer=data.candidates?.[0]?.content?.parts?.map(part=>part.text||'').join('');if(!answer)throw Error('Gemini не вернул команду');return JSON.parse(answer)}
async function runAiCommand(text){$('chat').querySelector('button').disabled=true;log('Gemini: разбираю команду…');try{const plan=await askGemini(text);if(!['add','move','cancel','show'].includes(plan.action))return log('Gemini не смог однозначно понять команду. Уточните дату, время или название.');if(plan.action==='add'){const title=String(plan.title||'').trim(),date=plan.date,start=plan.start,end=plan.end;if(!title||!validDate(date)||!validate(date,start,end))return log('Gemini не указал корректное название, дату и время. Уточните команду.');const item={id:crypto.randomUUID(),title,date,start,end,course:'',source:'draft',cancelled:false};ask('Добавить черновик?',[label(item)],()=>{state.events.push(item);save();monday=startOfWeek(day(date));render();log('Черновик добавлен. Подтвердите его отдельно для записи в Google Calendar.')});return}const ids=Array.isArray(plan.eventIds)?plan.eventIds:[],matches=state.events.filter(e=>!e.cancelled&&ids.includes(e.id));if(!matches.length)return log('Совпадений среди загруженных событий нет. Откройте нужную неделю или уточните название.');if(plan.action==='show')return log('Найдено:\n'+matches.map(label).join('\n'));if(plan.action==='move'&&(!validDate(plan.date)||!/^\d\d:\d\d$/.test(plan.start)))return log('Gemini не указал корректную новую дату и время.');const updates=matches.map(item=>{if(plan.action==='cancel')return {item};const duration=Number(item.end.slice(0,2))*60+Number(item.end.slice(3))-Number(item.start.slice(0,2))*60-Number(item.start.slice(3)),startMinutes=Number(plan.start.slice(0,2))*60+Number(plan.start.slice(3)),endMinutes=startMinutes+duration;if(duration<=0||startMinutes>=1440||endMinutes>=1440)return null;return {item,date:plan.date,start:plan.start,end:`${String(Math.floor(endMinutes/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}`}});if(updates.includes(null))return log('Новое время выходит за пределы дня. Уточните команду.');ask(plan.action==='cancel'?'Отменить события?':'Перенести события?',updates.map(x=>plan.action==='cancel'?`${label(x.item)} → отменить`:`${label(x.item)} → ${x.date} ${x.start}–${x.end}`),async()=>{for(const x of updates){if(x.item.googleId&&!accessToken)throw Error('Подключите Google для изменения события календаря');if(plan.action==='cancel'){if(x.item.googleId)await calendarRequest('DELETE',`/calendars/primary/events/${encodeURIComponent(x.item.googleId)}`);x.item.cancelled=true}else{const changed={...x.item,date:x.date,start:x.start,end:x.end};if(x.item.googleId)await calendarRequest('PATCH',`/calendars/primary/events/${encodeURIComponent(x.item.googleId)}`,toGoogle(changed));Object.assign(x.item,changed)}}save();if(plan.action==='move')monday=startOfWeek(day(plan.date));render();log('Изменения выполнены: '+updates.length)})}catch(err){log('Не удалось выполнить запрос к Gemini: '+err.message)}finally{$('chat').querySelector('button').disabled=false}}
$('chat').onsubmit=e=>{e.preventDefault();const text=$('command').value.trim();$('command').value='';log('Вы: '+text);if(geminiKey){runAiCommand(text);return}let m;if((m=text.match(/^(?:добавь|создай)\s+(.+)/i))){const time=parseTime(m[1]);if(!time)return log('Укажите время, например «добавь встречу завтра в 15:00».');const title=m[1].replace(/(?:^|\s)завтра(?=\s|$)/ig,'').replace(/\b\d{4}-\d{2}-\d{2}\b/g,'').replace(/\s+в\s+\d{1,2}(?::\d{2})?/i,'').trim();if(!title)return log('Не нашёл название события.');const date=parseDate(m[1]);const [h,min]=time.split(':').map(Number);const end=`${String((h+1)%24).padStart(2,'0')}:${String(min).padStart(2,'0')}`;if(end<=time)return log('Для позднего времени добавьте событие вручную.');const item={id:crypto.randomUUID(),title,date,start:time,end,course:'',source:'draft',cancelled:false};ask('Добавить черновик?',[label(item)],()=>{state.events.push(item);save();monday=startOfWeek(day(date));render();log('Черновик добавлен. Подтвердите его отдельно для записи в Google Calendar.')});return}
if((m=text.match(/^(?:перенеси|сдвинь|отмени|отменить)\s+(.+)/i))){const cancel=/^(?:отмени|отменить)/i.test(text),newTime=cancel?null:parseTime(m[1]);if(!cancel&&!newTime)return log('Укажите новое время, например «перенеси английский на 18:00».');const search=m[1].replace(/\s+на\s+\d{1,2}(?::\d{2})?/i,'').trim().toLowerCase();const matches=state.events.filter(x=>!x.cancelled&&(x.title.toLowerCase().includes(search)||x.course.toLowerCase().includes(search)));if(!matches.length)return log('Совпадений не найдено. Используйте название события или курса.');ask(`${cancel?'Отменить':'Перенести'} ${matches.length} событ${matches.length===1?'ие':'ия'}?`,matches.map(x=>`${label(x)} → ${cancel?'отменено':newTime}`),async()=>{for(const item of matches){if(item.googleId&&!accessToken)throw Error('Сначала подключите Google для изменения события календаря');if(cancel){if(accessToken&&item.googleId)await calendarRequest('DELETE',`/calendars/primary/events/${encodeURIComponent(item.googleId)}`);item.cancelled=true;save();render()}else{const [h,min]=item.end.split(':').map(Number),[sh,sm]=item.start.split(':').map(Number),duration=h*60+min-sh*60-sm,[nh,nm]=newTime.split(':').map(Number),endMinutes=nh*60+nm+duration;if(endMinutes>=1440)throw Error('Конец выходит за пределы дня');item.start=newTime;item.end=`${String(Math.floor(endMinutes/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}`;if(accessToken&&item.googleId)await calendarRequest('PATCH',`/calendars/primary/events/${encodeURIComponent(item.googleId)}`,toGoogle(item));save();render()}}save();render();log('Изменения подтверждены: '+matches.length)});return}log('Не понял команду. Примеры: «добавь встречу завтра в 15:00», «перенеси английский на 18:00», «отмени английский».')};
function toGoogle(e){const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;return {summary:e.title,description:e.course?`Курс: ${e.course}`:'',start:{dateTime:`${e.date}T${e.start}:00`,timeZone:tz},end:{dateTime:`${e.date}T${e.end}:00`,timeZone:tz}}}
async function calendarRequest(method,path,body){const r=await fetch('https://www.googleapis.com/calendar/v3'+path,{method,headers:{Authorization:'Bearer '+accessToken,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){const err=await r.text();throw Error(`Google API ${r.status}: ${err.slice(0,180)}`)}return r.status===204?null:r.json()}
async function loadGoogle(){if(!accessToken)return;const start=fmt(monday),end=fmt(shiftDate(monday,7));try{const q=new URLSearchParams({timeMin:new Date(start+'T00:00:00').toISOString(),timeMax:new Date(end+'T00:00:00').toISOString(),singleEvents:'true',maxResults:'250'});const data=await calendarRequest('GET','/calendars/primary/events?'+q);state.events=state.events.filter(x=>x.source==='draft'||!x.googleId);for(const g of data.items||[]){if(!g.start?.dateTime)continue;const d=new Date(g.start.dateTime),z=new Date(g.end.dateTime);state.events.push({id:crypto.randomUUID(),googleId:g.id,title:g.summary||'(без названия)',date:fmt(d),start:d.toTimeString().slice(0,5),end:z.toTimeString().slice(0,5),course:'',source:'calendar',cancelled:false})}save();render()}catch(e){alert('Не удалось загрузить календарь: '+e.message)}}
function gis(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>reject(Error('Google Identity Services не загрузился'));document.head.append(s)})}
$('settings').onclick=()=>{$('connection').textContent=accessToken?'Google подключён в этой вкладке.':'Вы работаете локально; события не отправляются в Google.';$('disconnect').hidden=!accessToken;$('closeConfig').textContent=accessToken?'Закрыть':'Продолжить без Google';$('config').showModal()};
$('closeConfig').onclick=()=>$('config').close();
$('connect').onclick=async()=>{try{await gis();tokenClient=google.accounts.oauth2.initTokenClient({client_id:googleClientId,scope:'https://www.googleapis.com/auth/calendar.events',callback:async response=>{if(response.error){$('connection').textContent='Google не подключён: '+response.error;return}state.events=state.events.filter(e=>!e.googleId);accessToken=response.access_token;$('config').close();render();await loadGoogle()}});tokenClient.requestAccessToken()}catch(e){$('connection').textContent='Не удалось подключить Google: '+e.message}};
$('disconnect').onclick=()=>{if(accessToken&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(accessToken,()=>{});accessToken='';state.events=state.events.filter(e=>!e.googleId);$('config').close();render()};render();
