const $ = id => document.getElementById(id);
const key = 'paper-calendar-v1';
const googleClientId = '477659561112-19g3hkek2d4bn408bed5feoa96nu19hq.apps.googleusercontent.com';
const state = JSON.parse(localStorage.getItem(key) || '{"events":[]}');
state.events=state.events.filter(e=>!e.googleId);
let monday = startOfWeek(new Date());
let accessToken = '';
let tokenClient;
let pending = null;
const fmt = d => [d.getFullYear(), String(d.getMonth()+1).padStart(2,'0'), String(d.getDate()).padStart(2,'0')].join('-');
const day = s => new Date(s+'T12:00:00');
function startOfWeek(d){let x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-(x.getDay()+6)%7);return x}
function shiftDate(d,n){let x=new Date(d);x.setDate(x.getDate()+n);return x}
function save(){localStorage.setItem(key,JSON.stringify({...state,events:state.events.filter(e=>!e.googleId)}))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(e){return `${e.date} ${e.start}–${e.end} · ${e.title}`}
function render(){const last=shiftDate(monday,6);$('week').textContent=`${monday.toLocaleDateString('ru',{day:'numeric',month:'long'})} — ${last.toLocaleDateString('ru',{day:'numeric',month:'long',year:'numeric'})}`;$('days').innerHTML=Array.from({length:7},(_,i)=>{const d=shiftDate(monday,i),date=fmt(d),events=state.events.filter(e=>e.date===date).sort((a,b)=>a.start.localeCompare(b.start));return `<div class="day"><div class="dayhead">${d.toLocaleDateString('ru',{weekday:'short'})}<b>${d.getDate()}</b></div>${events.map(e=>`<div class="event ${e.source==='draft'?'draft':''} ${e.cancelled?'cancelled':''}">${esc(e.start)}–${esc(e.end)}<strong>${esc(e.title)}</strong><small>${e.source==='draft'?'Черновик':'В календаре'}${e.course?' · '+esc(e.course):''}</small></div>`).join('')}</div>`}).join('');$('drafts').innerHTML=state.events.filter(e=>e.source==='draft').map(e=>`<div class="draft-card"><strong>${esc(e.title)}</strong>${esc(e.date)} · ${esc(e.start)}–${esc(e.end)}${e.course?' · '+esc(e.course):''}<div><button data-edit="${esc(e.id)}">Изменить</button><button data-publish="${esc(e.id)}">Подтвердить</button><button data-remove="${esc(e.id)}">Удалить</button></div></div>`).join('')||'<p>Черновиков пока нет.</p>';$('status').textContent=accessToken?'Google подключён':'Локальный режим'}
function ask(title,items,action){pending=action;$('confirm').querySelector('h2').textContent=title;$('details').innerHTML=items.map(s=>`<div class="detail">${esc(s)}</div>`).join('');$('confirm').showModal()}
function log(s){$('log').textContent+='\n\n'+s;$('log').scrollTop=$('log').scrollHeight}
function validate(date,start,end){return /^\d{4}-\d{2}-\d{2}$/.test(date)&&/^\d\d:\d\d$/.test(start)&&/^\d\d:\d\d$/.test(end)&&end>start}
$('prev').onclick=()=>{monday=shiftDate(monday,-7);render();loadGoogle()};$('next').onclick=()=>{monday=shiftDate(monday,7);render();loadGoogle()};$('today').onclick=()=>{monday=startOfWeek(new Date());render();loadGoogle()};$('date').value=fmt(new Date());
let photoImage=null, selection=null, dragStart=null, recognizer=null, photoUrl=null;
const canvas=$('crop'),ctx=canvas.getContext('2d');
function redraw(){if(!photoImage)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(photoImage,0,0,canvas.width,canvas.height);if(selection){ctx.fillStyle='#246f7040';ctx.strokeStyle='#246f70';ctx.lineWidth=3;ctx.fillRect(...selection);ctx.strokeRect(...selection)}}
function point(ev){const r=canvas.getBoundingClientRect();return {x:(ev.clientX-r.left)*canvas.width/r.width,y:(ev.clientY-r.top)*canvas.height/r.height}}
canvas.onpointerdown=ev=>{dragStart=point(ev);canvas.setPointerCapture(ev.pointerId)};
canvas.onpointermove=ev=>{if(!dragStart)return;const p=point(ev);selection=[Math.min(p.x,dragStart.x),Math.min(p.y,dragStart.y),Math.abs(p.x-dragStart.x),Math.abs(p.y-dragStart.y)];redraw()};
canvas.onpointerup=()=>{dragStart=null;$('recognize').hidden=!selection||selection[2]<10||selection[3]<5};
function loadPhoto(file){if(!file)return;if(!file.type.startsWith('image/')){$('ocrStatus').textContent='Нужен файл изображения.';return}const nextUrl=URL.createObjectURL(file),img=new Image();img.onload=()=>{if(photoUrl)URL.revokeObjectURL(photoUrl);photoUrl=nextUrl;photoImage=img;const scale=Math.min(1,1000/img.width);canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);selection=null;canvas.hidden=false;$('recognize').hidden=true;$('dropzone').classList.add('has-photo');$('dropzone').querySelector('strong').textContent='Фото загружено';$('dropzone').querySelector('span').textContent='Перетащите другое или нажмите для замены';redraw();$('ocrStatus').textContent='Выделите одну строку на фото.'};img.onerror=()=>{URL.revokeObjectURL(nextUrl);$('ocrStatus').textContent='Не удалось открыть изображение.'};img.src=nextUrl}
const dropzone=$('dropzone');
dropzone.onclick=()=>$('photo').click();
dropzone.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('photo').click()}};
$('photo').onchange=()=>{loadPhoto($('photo').files[0]);$('photo').value=''};
dropzone.ondragover=e=>{e.preventDefault();e.dataTransfer.dropEffect='copy';dropzone.classList.add('dragover')};
dropzone.ondragleave=e=>{if(!dropzone.contains(e.relatedTarget))dropzone.classList.remove('dragover')};
dropzone.ondrop=e=>{e.preventDefault();dropzone.classList.remove('dragover');loadPhoto([...e.dataTransfer.files].find(file=>file.type.startsWith('image/'))||e.dataTransfer.files[0])};
document.addEventListener('paste',e=>{const image=[...(e.clipboardData?.items||[])].find(item=>item.type.startsWith('image/'));if(!image)return;e.preventDefault();loadPhoto(image.getAsFile())});
async function ocrWorker(){if(recognizer)return recognizer;await new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/tesseract.js@6.0.1/dist/tesseract.min.js';script.onload=resolve;script.onerror=()=>reject(Error('Не удалось загрузить Tesseract.js'));document.head.append(script)});recognizer=await Tesseract.createWorker('rus',1,{logger:message=>{if(message.progress!==undefined)$('ocrStatus').textContent=`Загрузка OCR: ${Math.round(message.progress*100)}%`}});await recognizer.setParameters({tessedit_pageseg_mode:Tesseract.PSM.SINGLE_LINE});return recognizer}
$('recognize').onclick=async()=>{if(!selection)return;const [x,y,w,h]=selection;const piece=document.createElement('canvas');piece.width=Math.round(w);piece.height=Math.round(h);piece.getContext('2d').drawImage(canvas,x,y,w,h,0,0,w,h);$('recognize').disabled=true;$('ocrStatus').textContent='Загружаю русскую OCR-модель…';try{const worker=await ocrWorker();$('ocrStatus').textContent='Распознаю строку локально…';const result=await worker.recognize(piece);const found=result.data.text.trim();$('title').value=found;$('ocrStatus').textContent=found?'Результат помещён в название. Проверьте текст, дату и время перед добавлением.':'Не удалось прочесть строку. Выберите другой фрагмент или введите текст вручную.'}catch(err){$('ocrStatus').textContent='OCR не запустился: '+err.message+'. Введите текст вручную.'}finally{$('recognize').disabled=false}};
$('add').onsubmit=e=>{e.preventDefault();const title=$('title').value.trim(),date=$('date').value,start=$('start').value,end=$('end').value,course=$('course').value.trim();if(!validate(date,start,end))return alert('Проверьте дату и время: конец должен быть позже начала.');state.events.push({id:crypto.randomUUID(),title,date,start,end,course,source:'draft',cancelled:false});save();monday=startOfWeek(day(date));render();$('title').value='';$('course').value=''};
$('drafts').onclick=e=>{const b=e.target.closest('button');if(!b)return;const id=b.dataset.edit||b.dataset.publish||b.dataset.remove;const item=state.events.find(x=>x.id===id);if(!item)return;if(b.dataset.edit){const title=prompt('Название',item.title);if(title===null)return;const date=prompt('Дата ГГГГ-ММ-ДД',item.date);if(date===null)return;const start=prompt('Начало ЧЧ:ММ',item.start);if(start===null)return;const end=prompt('Конец ЧЧ:ММ',item.end);if(end===null)return;if(!title.trim()||!validate(date,start,end))return alert('Проверьте название, дату и время.');Object.assign(item,{title:title.trim(),date,start,end});save();render()}else if(b.dataset.remove){ask('Удалить черновик?',[label(item)],()=>{state.events=state.events.filter(x=>x.id!==id);save();render()})}else ask('Создать событие?',[label(item)],async()=>{if(accessToken){const result=await calendarRequest('POST','/calendars/primary/events',toGoogle(item));item.googleId=result.id}item.source='calendar';save();render()})};
$('no').onclick=()=>$('confirm').close();$('yes').onclick=async()=>{const action=pending;pending=null;$('confirm').close();if(!action)return;try{await action()}catch(err){alert('Изменение не выполнено: '+err.message)}};
function parseTime(text){const m=text.match(/(?:в|на)\s*(\d{1,2})(?::(\d{2}))?/i);if(!m)return null;const h=+m[1],min=+(m[2]||0);return h<24&&min<60?`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`:null}
function parseDate(text){const iso=text.match(/\b(\d{4}-\d{2}-\d{2})\b/);if(iso)return iso[1];if(/завтра/i.test(text))return fmt(shiftDate(new Date(),1));return fmt(new Date())}
$('chat').onsubmit=e=>{e.preventDefault();const text=$('command').value.trim();$('command').value='';log('Вы: '+text);let m;if((m=text.match(/^(?:добавь|создай)\s+(.+)/i))){const time=parseTime(m[1]);if(!time)return log('Укажите время, например «добавь встречу завтра в 15:00».');const title=m[1].replace(/(?:^|\s)завтра(?=\s|$)/ig,'').replace(/\b\d{4}-\d{2}-\d{2}\b/g,'').replace(/\s+в\s+\d{1,2}(?::\d{2})?/i,'').trim();if(!title)return log('Не нашёл название события.');const date=parseDate(m[1]);const [h,min]=time.split(':').map(Number);const end=`${String((h+1)%24).padStart(2,'0')}:${String(min).padStart(2,'0')}`;if(end<=time)return log('Для позднего времени добавьте событие вручную.');const item={id:crypto.randomUUID(),title,date,start:time,end,course:'',source:'draft',cancelled:false};ask('Добавить черновик?',[label(item)],()=>{state.events.push(item);save();monday=startOfWeek(day(date));render();log('Черновик добавлен. Подтвердите его отдельно для записи в Google Calendar.')});return}
if((m=text.match(/^(?:перенеси|сдвинь|отмени|отменить)\s+(.+)/i))){const cancel=/^(?:отмени|отменить)/i.test(text),newTime=cancel?null:parseTime(m[1]);if(!cancel&&!newTime)return log('Укажите новое время, например «перенеси английский на 18:00».');const search=m[1].replace(/\s+на\s+\d{1,2}(?::\d{2})?/i,'').trim().toLowerCase();const matches=state.events.filter(x=>!x.cancelled&&(x.title.toLowerCase().includes(search)||x.course.toLowerCase().includes(search)));if(!matches.length)return log('Совпадений не найдено. Используйте название события или курса.');ask(`${cancel?'Отменить':'Перенести'} ${matches.length} событ${matches.length===1?'ие':'ия'}?`,matches.map(x=>`${label(x)} → ${cancel?'отменено':newTime}`),async()=>{for(const item of matches){if(item.googleId&&!accessToken)throw Error('Сначала подключите Google для изменения события календаря');if(cancel){if(accessToken&&item.googleId)await calendarRequest('DELETE',`/calendars/primary/events/${encodeURIComponent(item.googleId)}`);item.cancelled=true;save();render()}else{const [h,min]=item.end.split(':').map(Number),[sh,sm]=item.start.split(':').map(Number),duration=h*60+min-sh*60-sm,[nh,nm]=newTime.split(':').map(Number),endMinutes=nh*60+nm+duration;if(endMinutes>=1440)throw Error('Конец выходит за пределы дня');item.start=newTime;item.end=`${String(Math.floor(endMinutes/60)).padStart(2,'0')}:${String(endMinutes%60).padStart(2,'0')}`;if(accessToken&&item.googleId)await calendarRequest('PATCH',`/calendars/primary/events/${encodeURIComponent(item.googleId)}`,toGoogle(item));save();render()}}save();render();log('Изменения подтверждены: '+matches.length)});return}log('Не понял команду. Примеры: «добавь встречу завтра в 15:00», «перенеси английский на 18:00», «отмени английский».')};
function toGoogle(e){const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;return {summary:e.title,description:e.course?`Курс: ${e.course}`:'',start:{dateTime:`${e.date}T${e.start}:00`,timeZone:tz},end:{dateTime:`${e.date}T${e.end}:00`,timeZone:tz}}}
async function calendarRequest(method,path,body){const r=await fetch('https://www.googleapis.com/calendar/v3'+path,{method,headers:{Authorization:'Bearer '+accessToken,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok){const err=await r.text();throw Error(`Google API ${r.status}: ${err.slice(0,180)}`)}return r.status===204?null:r.json()}
async function loadGoogle(){if(!accessToken)return;const start=fmt(monday),end=fmt(shiftDate(monday,7));try{const q=new URLSearchParams({timeMin:new Date(start+'T00:00:00').toISOString(),timeMax:new Date(end+'T00:00:00').toISOString(),singleEvents:'true',maxResults:'250'});const data=await calendarRequest('GET','/calendars/primary/events?'+q);state.events=state.events.filter(x=>x.source==='draft'||!x.googleId);for(const g of data.items||[]){if(!g.start?.dateTime)continue;const d=new Date(g.start.dateTime),z=new Date(g.end.dateTime);state.events.push({id:crypto.randomUUID(),googleId:g.id,title:g.summary||'(без названия)',date:fmt(d),start:d.toTimeString().slice(0,5),end:z.toTimeString().slice(0,5),course:'',source:'calendar',cancelled:false})}save();render()}catch(e){alert('Не удалось загрузить календарь: '+e.message)}}
function gis(){return new Promise((resolve,reject)=>{if(window.google?.accounts?.oauth2)return resolve();const s=document.createElement('script');s.src='https://accounts.google.com/gsi/client';s.onload=resolve;s.onerror=()=>reject(Error('Google Identity Services не загрузился'));document.head.append(s)})}
$('settings').onclick=()=>{$('connection').textContent=accessToken?'Google подключён в этой вкладке.':'Вы работаете локально; события не отправляются в Google.';$('disconnect').hidden=!accessToken;$('closeConfig').textContent=accessToken?'Закрыть':'Продолжить без Google';$('config').showModal()};
$('closeConfig').onclick=()=>$('config').close();
$('connect').onclick=async()=>{try{await gis();tokenClient=google.accounts.oauth2.initTokenClient({client_id:googleClientId,scope:'https://www.googleapis.com/auth/calendar.events',callback:async response=>{if(response.error){$('connection').textContent='Google не подключён: '+response.error;return}state.events=state.events.filter(e=>!e.googleId);accessToken=response.access_token;$('config').close();render();await loadGoogle()}});tokenClient.requestAccessToken()}catch(e){$('connection').textContent='Не удалось подключить Google: '+e.message}};
$('disconnect').onclick=()=>{if(accessToken&&window.google?.accounts?.oauth2)google.accounts.oauth2.revoke(accessToken,()=>{});accessToken='';state.events=state.events.filter(e=>!e.googleId);$('config').close();render()};render();
